package dam.pmdm.tarea2_gutierrezruiz_francisco

// Clase que representa un pikmin
data class Pikmin(
    val nombre: String,
    val familia: String,
    val nombreCientifico: String,
    val esTerrestre: Boolean,
    val esAcuatico: Boolean,
    val esAereo: Boolean,
    val descripcion: String,
    val caracteristica1: String,
    val caracteristica2: String,
    val caracteristica3: String,
    val imagen: Int
)

// Lista de pikmins
val PIKMINS: List<Pikmin> = listOf(

    Pikmin(
        nombre = "Pikmin rojo",
        familia = "Pikmin",
        nombreCientifico = "Pikminidae rubrus",
        esTerrestre = true,
        esAcuatico = false,
        esAereo = false,
        descripcion = "Cuerpo de color escarlata y nariz puntiaguda. Además de los rasgos vegetales propios de su especie, presentan características animales como un fuerte espíritu combativo y un grado elevado de curiosidad. Tienen una gran capacidad de adaptación, pues no solo son resistentes al calor extremo, sino que también suelen habitar en una gran variedad de ecosistemas.",
        caracteristica1 = "Inmunidad al fuego: La epidermis y fibras musculares se componen de una celulosa ignífuga, lo que les permite tener inmunidad al calor y al fuego.",
        caracteristica2 = "Alta capacidad ofensiva: Las puntiagudas protuberancias nasales son la causa de la fuerza sobresaliente que los caracteriza.",
        caracteristica3 = "",
        imagen = R.drawable.red_pikmin
    ),
    Pikmin(
        nombre = "Pikmin amarillo",
        familia = "Pikmin",
        nombreCientifico = "Pikminidae auribus",
        esTerrestre = true,
        esAcuatico = false,
        esAereo = false,
        descripcion = "Cuerpo de color amarillo y un par de lamelas semejantes a orejas que les permiten cavar con rapidez y alcanzar grandes alturas al ser lanzados. Otro rasgo que los distingue es la capacidad de sus cuerpos de conducir la electricidad. Además no solo son resistentes a ella, sino que parecen disfrutarla.",
        caracteristica1 = "Resistencia a la electricidad: Se ha comprobado que, si son expuestos a la electricidad estando en fase de hoja, sus hojas florecerán. Por el contrario, otros tipos de Pikmin terminarían electrocutados si fueran expuestos a dicho elemento.",
        caracteristica2 = "Capacidad de vuelo elevado: Poseen dos lamelas a los costados de la cabeza que les permiten alcanzar grandes alturas cuando son lanzados. La distancia que recorren es la misma.",
        caracteristica3 = "Excelentes cavadores: Cavan más rápido que otros tipos de Pikmin.",
        imagen = R.drawable.yellow_pikmin
    ),
    Pikmin(
        nombre = "Pikmin azul",
        familia = "Pikmin",
        nombreCientifico = "Pikminidae caerula",
        esTerrestre = true,
        esAcuatico = true,
        esAereo = false,
        descripcion = "Cuerpo de color azul y expresión facial indescifrable. A diferencia de la mayoría de las especies radiambulares, que no pueden respirar bajo el agua, los Pikmin azules cuentan con branquias que se confunden con una boca. Esas branquias les permiten sobrevivir en ecosistemas acuáticos y terrestres.",
        caracteristica1 = "Respiración bajo el agua: Tienen unas branquias en la cabeza que se confunden con una boca. Dichas branquias les permiten respirar bajo el agua.",
        caracteristica2 = "Excelentes nadadores: Son capaces de combatir criaturas bajo el agua.",
        caracteristica3 = "",
        imagen = R.drawable.blue_pikmin
    ),
    Pikmin(
        nombre = "Pikmin blanco",
        familia = "Pikmin",
        nombreCientifico = "Pikminidae venalbius",
        esTerrestre = true,
        esAcuatico = false,
        esAereo = false,
        descripcion = "Cuerpo de color blanco y ojos rojos. Sus pequeños cuerpos segregan un potente veneno, lo que a su vez los hace inmunes a ciertos venenos. Las semillas de Pikmin blancos se pueden obtener por medio de brotes rebotadores marfil que solo crecen en regiones subterráneas.",
        caracteristica1 = "Inmunidad al veneno: Son muy resistentes a los venenos y son inmunes a gases y esporas venenosos.",
        caracteristica2 = "Cuerpos venenosos: Resultan letales para las criaturas que los ingieran.",
        caracteristica3 = "Velocidad: Son los más veloces de todos los Pikmin. Sus pequeños cuerpos no causan mucho daño al atacar.",
        imagen = R.drawable.white_pikmin
    ),
    Pikmin(
        nombre = "Pikmin morado",
        familia = "Pikmin",
        nombreCientifico = "Pikminidae yokozunum",
        esTerrestre = true,
        esAcuatico = false,
        esAereo = false,
        descripcion = "Cuerpo robusto y resistente. Son más fuertes y grandes que el resto de su especie. Pesan 10 veces más que cualquier otro Pikmin. Al igual que los Pikmin blancos, solo pueden nacer a partir de brotes rebotadores que solo se encuentran en regiones subterráneas, por lo que son considerados una especie única.",
        caracteristica1 = "Peso: Pesan 10 veces más que los otros Pikmin. Son tan pesados que, al impactar contra el suelo, crean ondas gravitatorias que puede causar daño. Debido a su peso elevado, son más lentos.",
        caracteristica2 = "Gran capacidad de carga: Sus fibras musculares son muy densas, lo que les permite tener la fuerza de 10 Pikmin normales. El alcance de su ataque es similar al de los Pikmin rojos. La capacidad de carga de 10 Pikmin normales es igual a la de 1 Pikmin morado.",
        caracteristica3 = "Nacen en el subsuelo: Solo nacen en el subsuelo al ser lanzados en brotes rebotadores violetas. Este proceso es similar al de los Pikmin blancos al ser lanzados a los brotes rebotadores marfil.",
        imagen = R.drawable.purple_pikmin
    ),
    Pikmin(
        nombre = "Pikmin pétreo",
        familia = "Pikmin",
        nombreCientifico = "Pikminidae habisaxum",
        esTerrestre = true,
        esAcuatico = false,
        esAereo = false,
        descripcion = "Tipo de Pikmin parasitario llamado Ermikmin que toma como huésped una piedra y, de manera similar a una semilla que echa raíces a través de las grietas de una roca, las raíces del Pikmin penetran la piedra.",
        caracteristica1 = "Inquebrantables: Dado que sus cuerpos están hechos de rocas son casi indestructibles, pero pueden ser destruidos si son aplastados sobre superficies duras.",
        caracteristica2 = "Robustos: Tienen cuerpos muy robustos. ¡Son capaces de romper superficies de cristal!",
        caracteristica3 = "No adherentes: Gracias a la superficie áspera de sus cuerpos, no se pueden adherir a criaturas enemigas y, por el contrario, se lanzan hacia ellas para atacar con todo el cuerpo.",
        imagen = R.drawable.rock_pikmin
    ),
    Pikmin(
        nombre = "Pikmin alado",
        familia = "Pikmin",
        nombreCientifico = "Pikminidae volarosa",
        esTerrestre = false,
        esAcuatico = false,
        esAereo = true,
        descripcion = "Cuerpo de color rosa y prominentes ojos azules que parecen lentes. Se desplazan ágilmente por los aires con sus alas, pero sus ataques no causan mucho daño.",
        caracteristica1 = "Capacidad de vuelo: Son el único tipo de Pikmin que pueden volar.",
        caracteristica2 = "Ataques débiles: Dado que tienen pequeños cuerpos no causan mucho daño al atacar. Sin embargo, son muy persistentes y, una vez que comienzan a atacar, no pararán de hacerlo.",
        caracteristica3 = "",
        imagen = R.drawable.winged_pikmin
    ),
    Pikmin(
        nombre = "Pikmin gélido",
        familia = "Pikmin",
        nombreCientifico = "Pikminidae habiglacius",
        esTerrestre = true,
        esAcuatico = false,
        esAereo = false,
        descripcion = "Pertenecen a un subtipo parasitario de Pikmin llamado Ermikmin. Obtienen y mantienen su cuerpo a través de un proceso que utiliza su núcleo de baja temperatura para generar constantemente hielo nuevo de la humedad del ambiente.",
        caracteristica1 = "Propiedades de congelamiento: Congelan a su presa al golpear su cuerpo gélido contra ellas. También flotan en la superficie del agua. Al agruparse, son capaces de congelar grandes extensiones de agua",
        caracteristica2 = "Inmunidad al frío: Son inmunes a las temperaturas frías y no pueden ser congelados. Sin embargo, son muy vulnerables al fuego y pueden derretirse rápidamente. Eso significa que las llamas les producirán daño más rápidamente que a otros Pikmin.",
        caracteristica3 = "",
        imagen = R.drawable.ice_pikmin
    ),
    Pikmin(
        nombre = "Pikmin luminoso",
        familia = "Pikmin",
        nombreCientifico = "Pikminidae supravelum",
        esTerrestre = true,
        esAcuatico = true,
        esAereo = false,
        descripcion = "Cuerpo de color verde radiante. Al florecer la hoja que tienen en la cabeza, esta toma una forma de estrella. Tienen varias características que los distinguen de los otros tipos de Pikmin, una de ellas es que en vez de brotar de cebollas brotan de lumilomas que solo se encuentran en la noche y en regiones subterráneas.",
        caracteristica1 = "Viven en lumilomas en vez de cebollas. No tienen pies y flotan en el aire. Son inmunes a muchos elementos que afectan a otros tipos de Pikmin.",
        caracteristica2 = "Actividad nocturna y en regiones subterráneas: Son una especie nocturna. Sus actividades se centran en proteger a las lumilomas de los depredadores. Durante el día toman forma de semillas y permanecen en un estado de letargo. Durante la noche y en regiones subterráneas, se encuentran en su forma regular.",
        caracteristica3 = "Comportamiento inusual: Muestran comportamientos que no se observan en otras criaturas. Por ejemplo, pueden teletransportarse a lugares remotos. También tienen la capacidad de fusionarse en grupo para formar una esfera de luz intensa.",
        imagen = R.drawable.glow_pikmin
    ),
    Pikmin(
        nombre = "Bulbo",
        familia = "Gusarapérridos",
        nombreCientifico = "Oculus kageyamii russus",
        esTerrestre = true,
        esAcuatico = false,
        esAereo = false,
        descripcion = "Tiene el abdomen escarlata salpicado de motas blancas. Sus hábitos son nocturnos, por lo que de día suelen encontrarse durmiendo. Si son despertados, intentarán engullir cualquier cosa que tengan enfrente. Hay una gran variedad de gusarapérridos, y se considera que están en la cima de la cadena alimenticia.",
        caracteristica1 = "Nocturnos: Duermen durante el día y solo se despiertan si se sienten amenazados, por ejemplo, si perciben que alguien entra a su territorio. Al ponerse el sol salen a cazar.",
        caracteristica2 = "Consejos para identificarlos: Conforme envejecen, su tonalidad se oscurece. Las motas blancas del abdomen les permiten reconocer a otros de su especie. Se han registrado casos en los que accidentalmente se alimentan de larvas que no presentan motas blancas.",
        caracteristica3 = "Ojos prominentes: Han desarrollado globos oculares prominentes que les permiten tener una mejor visión nocturna, pero, debido al gran tamaño que han alcanzado, les es imposible cerrarlos por completo. La forma en la que estas criaturas parpadean es por medio de la expansión y contracción del iris.",
        imagen = R.drawable.bulborb
    ),
    Pikmin(
        nombre = "Liendre astada",
        familia = "Excavarópteros",
        nombreCientifico = "Trilobitins reversa",
        esTerrestre = true,
        esAcuatico = false,
        esAereo = false,
        descripcion = "Poseen un caparazón duro que les protege la cabeza. Pero, si bien los ataques frontales no les causan daño, su parte trasera es muy vulnerable. Esta característica la distingue de la liendre zamacuca pinchosa, la primera especie de la familia que fue descubierta.",
        caracteristica1 = "Una cabeza bien protegida: Gracias al caparazón resistente que le protege la cabeza tiende a arremeter frontalmente tanto contra depredadores como contra posibles presas. Desafortunadamente para ellas, su abdomen queda ampliamente desprotegido. Suelen esconderse en la tierra durante el día.",
        caracteristica2 = "Boca con forma de aguja: Poseen partes de la boca que son alargadas y tienen forma de aguja, lo que les permiten succionar fluidos de la presa que atraviesan.",
        caracteristica3 = "",
        imagen = R.drawable.joustmite
    ),
    Pikmin(
        nombre = "Pisaátomos hoja",
        familia = "Pisaátomos",
        nombreCientifico = "Rus pseudoarbicans",
        esTerrestre = true,
        esAcuatico = true,
        esAereo = false,
        descripcion = "Tipo de pisaátomo acuático que se protege de depredadores al confundirse con una hoja verde similar a la de los árboles de hojas anchas. Si bien no puede flotar, el pisaátomos hoja puede nadar con facilidad girando su cuerpo en el agua.",
        caracteristica1 = "Mimetismo: Imita a las hojas comunes para poder ocultarse de posibles depredadores. Su lengua en forma de tallo le permite succionar néctar.",
        caracteristica2 = "Alas vestigiales: Las partes del cuerpo en forma de hoja evolucionaron de sus alas vestigiales, las cuales emiten un sonido similar al de una campana.",
        caracteristica3 = "",
        imagen = R.drawable.skitter_leaf
    ),
    Pikmin(
        nombre = "Insecto noducristal",
        familia = "Nodúlidos",
        nombreCientifico = "Hierodeciderit crystallosum",
        esTerrestre = true,
        esAcuatico = false,
        esAereo = false,
        descripcion = "Cuerpo plano, brilloso y negro. Llevan pequeñas rocas a cuestas. Sus antenas y los finos vellos en sus patas han evolucionado para ayudarlos a detectar peligro a sus alrededores, incluso en la oscuridad. Tienden a compartir su hábitat con las larvas de sapo patilargo para asegurarse una amplia provisión de rocas.",
        caracteristica1 = "Llevar objetos: Tienen el lomo cóncavo. Esto les permite llevar objetos fácilmente, como rocas pequeñas. Se ha observado que parecen estar vistiendo pequeños sombreros cuando llevan cosas a cuestas.",
        caracteristica2 = "Arrojar objetos: Se defienden de depredadores arrojando los objetos que llevan a cuestas.",
        caracteristica3 = "",
        imagen = R.drawable.skutterchuck
    ),
    Pikmin(
        nombre = "Pirobabosa",
        familia = "Babósidos",
        nombreCientifico = "Sulucina vulcanis",
        esTerrestre = true,
        esAcuatico = false,
        esAereo = false,
        descripcion = "Especie de gasterópodo terrestre que se protege a sí misma con llamas. En vez de tener un caparazón tradicional, están recubiertas de una mucosa inflamable. Si su llama se extingue les llevará más de un día y medio volver a encenderla.",
        caracteristica1 = "Recubiertas en llamas: Uutilizan una mucosa inflamable que les recubre el cuerpo para protegerlas de depredadores. Se aíslan de las llamas que les recubren el cuerpo segregando mucosa constantemente.",
        caracteristica2 = "Lengua alargada: Utilizan su lengua alargada para atrapar y enredar a su presa.",
        caracteristica3 = "",
        imagen = R.drawable.pyroclasmic_slooch
    ),
    Pikmin(
        nombre = "Estaticán lanudo",
        familia = "Estatidentios",
        nombreCientifico = "Porcellus barbavolta",
        esTerrestre = true,
        esAcuatico = false,
        esAereo = false,
        descripcion = "Clase de ratón capaz de generar energía estática frotando los vellos de su barba. Además son mamíferos y, por lo tanto, bastante inusuales en este planeta. Es necesario realizar más investigaciones sobre estas criaturas dado que su mera existencia podría dar lugar al surgimiento de una taxonomía de fauna completamente nueva.",
        caracteristica1 = "Generadores de electricidad: Pueden almacenar electricidad en la barba al frotar sus vellos. Este comportamiento hace que se acumule energía estática que ellos luego pueden descargar.",
        caracteristica2 = "Lactancia: Poseen vellos que les recubren todo el cuerpo para poder mantener una temperatura corporal estable, pero su abdomen es menos velludo. Suelen amamantar a su cría.",
        caracteristica3 = "",
        imagen = R.drawable.bearded_amprat
    ),
    Pikmin(
        nombre = "Bulbo emperatriz",
        familia = "Gusarapérridos",
        nombreCientifico = "Oculus kageyamii matriarchia (hipertrofia, gravidez)",
        esTerrestre = true,
        esAcuatico = false,
        esAereo = false,
        descripcion = "Cuando se cumplen ciertas condiciones en el medioambiente, como la disminución repentina de las especies que les sirven de alimento, la hembra de mayor tamaño de los gusarapérridos de la zona asume el papel de matriarca del grupo. Como resultado, el ovisaco del gusarapérrido hembra se hincha hasta alcanzar enormes proporciones. En ese estado, los nuevos bulbos emperatrices producen un largo número de larvas.",
        caracteristica1 = "Nacimiento de las larvas: Puede dar a luz a un gran número de larvas, formando un grupo de hasta 50 miembros. Una hipótesis establece que este proceso es una estrategia de supervivencia y que las larvas nuevas tienen la tarea de diseminarse por otras zonas con abundantes fuentes de alimento. Sin embargo, otra hipótesis sugiere que las larvas son generadas como fuente nutritiva de emergencia.",
        caracteristica2 = "Rodar: Su cuerpo es demasiado grande como para desplazarse caminando. Por lo tanto, se arrastran y ruedan por el suelo hacia adelante y hacia atrás para poder desplazarse. No es inusual que ruede accidentalmente encima de una larva de bulbo sin darse cuenta, dado que las larvas de bulbo recién nacidas no poseen manchas rojas.",
        caracteristica3 = "",
        imagen = R.drawable.empress_bulblax
    ),
    Pikmin(
        nombre = "Espectro acuático",
        familia = "Desconocida",
        nombreCientifico = "Amphibio sapiens",
        esTerrestre = true,
        esAcuatico = false,
        esAereo = false,
        descripcion = "Todos los informes existentes sobre los espectros acuáticos los describen como seres transparentes, viscosos, con cuerpo gelatinoso que ligeramente se asemeja al cuerpo humano. Se desplazan haciendo rodar dos rocas cilíndricas y utilizando sus extremidades para maniobrar las rocas y perseguir a su presa. Sin embargo, dado que se los ha visto solo unas pocas veces, los espectros acuáticos continúan siendo un gran misterio.",
        caracteristica1 = "Cuerpo transparente: Poseen cuerpos que no son ni líquidos ni sólidos, lo que hace imposible aplicar cualquier criterio de clasificación tradicional en ellos.",
        caracteristica2 = "Rocas cilíndricas: Generalmente se desplazan utilizando rocas que son predominantemente basálticas pero que también incluyen pequeñas cantidades de otros minerales raros, como el níquel y el cobalto.",
        caracteristica3 = "Características bípedas: Se han reportado instancias en las que se vieron caminando en dos patas.",
        imagen = R.drawable.waterwraith
    ),
    Pikmin(
        nombre = "Lumiloma",
        familia = "Desconocida",
        nombreCientifico = "Collux aeternium",
        esTerrestre = true,
        esAcuatico = false,
        esAereo = false,
        descripcion = "Actúan como nidos e incubadoras de los Pikmin luminosos. Solo aparecen durante la noche en lugares donde haya habido una cebolla durante el día. Su color verde radiante atrae a criaturas nocturnas.",
        caracteristica1 = "Nidos de Pikmin luminosos: Los Pikmin luminosos viven dentro de las lumilomas. Si se transportan a ella píldoras lumínicas, brotarán más Pikmin luminosos.",
        caracteristica2 = "Señueloma: Es una fase temprana de las lumilomas. A pesar de su menor tamaño, atrae de igual manera a criaturas nocturnas.",
        caracteristica3 = "Néctar luminoso: Segregan un componente rico en enzimas de degradación.",
        imagen = R.drawable.lumiknoll
    ),
    Pikmin(
        nombre = "Cepucranco",
        familia = "Cepucránquidos",
        nombreCientifico = "Brachyurices esurio",
        esTerrestre = true,
        esAcuatico = true,
        esAereo = false,
        descripcion = "Son cangrejos anfibios con pinzas asimétricas. La pinza derecha de mayor tamaño puede regenerarse después de desprenderse al cambiar la piel, incluso después de haberse perdido por completo. Curiosamente, no solo su cuerpo se asemeja al de una cebolla, sino que también huelen similar a ella.",
        caracteristica1 = "Pinza grande: Utilizan su gran pinza derecha para atrapar a sus presas, defenderse de posibles depredadores y producir los castañeteos del llamado característico en época de apareamiento.",
        caracteristica2 = "Expulsar burbujas: Cuando están en la tierra expulsan burbujas a través de unas válvulas especiales para descargar agua que poseen en la parte trasera de su boca. Para respirar, absorben oxígeno a través de las branquias que parecen mejillas.",
        caracteristica3 = "",
        imagen = R.drawable.peckish_aristocrab
    ),
    Pikmin(
        nombre = "Comején acuático",
        familia = "Comejantes",
        nombreCientifico = "Narrolingus piscatum",
        esTerrestre = false,
        esAcuatico = true,
        esAereo = false,
        descripcion = "Muchos piensan que los comejenes acuáticos no están del todo desarrollados, dado que poseen ojos grandes y no tienen aletas. El hecho es que esa es la fisonomía normal en la especie adulta. Los comejenes acuáticos utilizan su larga aleta caudal para atacar de forma agresiva a su presa cuando ella ingresa al agua.",
        caracteristica1 = "Saltar fuera del agua: A veces utilizan su larga aleta caudal para propulsarse fuera del agua y atrapar a su presa.",
        caracteristica2 = "Nado en grupo: Tienden a nadar en grupo para aumentar la probabilidad de atrapar presas al cazar.",
        caracteristica3 = "Coloración durante el apareamiento: Durante la época de apareamiento sus costados normalmente de color amarillo, se vuelven de color rosa fuerte.",
        imagen = R.drawable.puckering_blinnow
    ),
    Pikmin(
        nombre = "Acuatirador",
        familia = "Tiradores",
        nombreCientifico = "Gerridus clavomacula",
        esTerrestre = false,
        esAcuatico = true,
        esAereo = false,
        descripcion = "Patinan sobre el agua. Se alimentan de plancton que absorben, junto con el agua, a través de su boca en forma de tubo. Son territoriales y utilizan el agua como arma contra los pequeños insectos que se aproximan.",
        caracteristica1 = "Flotar en el agua: Sus patas están cubiertas por vellos hidrófobos los cuales crean tensión superficial que les permite flotar en el agua.",
        caracteristica2 = "Disparar agua: Succionan agua a través de una probóscide en forma de tubo y la escupen hacia los depredadores que ingresen en su territorio.",
        caracteristica3 = "",
        imagen = R.drawable.skeeterskate
    ),
    Pikmin(
        nombre = "Berberéchido soplón",
        familia = "Molúsquidos",
        nombreCientifico = "Molluschid minionicus",
        esTerrestre = true,
        esAcuatico = true,
        esAereo = false,
        descripcion = "Son moluscos anfibios con grandes branquias que se asemejan a una flor. Sus ojos no sobresalen de manera tan pronunciada como los de otras especies de la familia de los molúsquidos, que fueron evolucionando cada vez más alejados del caparazón. Los berberéchidos soplones poseen órganos reproductivos tanto masculinos como femeninos.",
        caracteristica1 = "Lengua larga y delgada: Utilizan sus distintivas lenguas para detectar a sus posibles presas. Dicha lengua está dividida en seis terminaciones diferentes, lo que les permite capturar múltiples presas de una sola vez.",
        caracteristica2 = "Expulsar tinta: Pueden expulsar tinta de su cuerpo al percibirse en peligro.",
        caracteristica3 = "",
        imagen = R.drawable.toady_bloyster
    ),
    Pikmin(
        nombre = "Burbujero",
        familia = "Cefalopómpados",
        nombreCientifico = "Opisteuthidae iaciobulla",
        esTerrestre = true,
        esAcuatico = true,
        esAereo = false,
        descripcion = "Expulsan burbujas por la boca y el cuerpo. Pueden parecerse a los pulpos, pero, en realidad, se acercan más a las estrellas de mar en cuanto a su anatomía. Poseen cinco brazos que, al estar distribuidos de forma radial en la parte redonda de su cuerpo, forman una estrella. Viven principalmente cerca del agua, pero también pueden sobrevivir en la tierra.",
        caracteristica1 = "Expulsar burbujas: Se inflan y expulsan burbujas para ahuyentar a los depredadores que se aproximan. Este comportamiento ocurre principalmente para proteger a los huevos durante la época de desove.",
        caracteristica2 = "Cuerpo elástico: Poseen 12 puntos en su torso elástico desde los cuales pueden expulsar burbujas.",
        caracteristica3 = "",
        imagen = R.drawable.waddlepus
    ),
    Pikmin(
        nombre = "Verraco volador",
        familia = "Verracos",
        nombreCientifico = "Sus inflata",
        esTerrestre = false,
        esAcuatico = false,
        esAereo = true,
        descripcion = "Utilizan el hidrógeno que generan internamente para inflar una vejiga flotatoria y así se mantienen en el aire. Expulsan aire a través de unos respiraderos.",
        caracteristica1 = "Capacidad de vuelo: Utilizan el hidrógeno que generan internamente para inflar una vejiga flotatoria y mantenerse en el aire. Mantienen la flotabilidad orientando las aletas y expulsando aire a través de los respiraderos que tienen a los costados.",
        caracteristica2 = "Capacidad de soplar aire: Soplan aire sobre sus presas para alimentarse y también para alejar enemigos.",
        caracteristica3 = "",
        imagen = R.drawable.puffy_blowhog
    ),
    Pikmin(
        nombre = "Moscardón ladrón",
        familia = "Escarpánidos",
        nombreCientifico = "Scarpanica kesperens",
        esTerrestre = false,
        esAcuatico = false,
        esAereo = true,
        descripcion = "Esta especie desarrolló enormemente sus antenas y ahora las usan para volar y atrapar Pikmin. La superficie de sus cuerpos se compone de delgadas capas que interfieren con la luz y dan el efecto visual de una coloración verde brillante.",
        caracteristica1 = "Instinto de aprisionar: Usan sus prolongadas antenas para volar y atrapar Pikmin.",
        caracteristica2 = " ",
        caracteristica3 = "",
        imagen = R.drawable.swooping_snitchbug
    )

)
